require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 60
